//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanweb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebSiteBanNonEntities : DbContext
    {
        public WebSiteBanNonEntities()
            : base("name=WebSiteBanNonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_anhchitietsanpham> tbl_anhchitietsanpham { get; set; }
        public DbSet<tbl_giohang> tbl_giohang { get; set; }
        public DbSet<tbl_Hgiohang> tbl_Hgiohang { get; set; }
        public DbSet<tbl_Hmember> tbl_Hmember { get; set; }
        public DbSet<tbl_member> tbl_member { get; set; }
        public DbSet<tbl_nhasanxuat> tbl_nhasanxuat { get; set; }
        public DbSet<tbl_sanpham> tbl_sanpham { get; set; }
        public DbSet<tbl_slider> tbl_slider { get; set; }
    }
}
