//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hmember
    {
        public int Id { get; set; }
        public string TenDangNhap { get; set; }
        public string TenDangNhap_Cu { get; set; }
        public string MatKhau { get; set; }
        public string MatKhau_Cu { get; set; }
        public string QuyenHan { get; set; }
        public string QuyenHan_Cu { get; set; }
        public string TenKhachHang { get; set; }
        public string TenKhachHang_Cu { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<System.DateTime> NgaySinh_Cu { get; set; }
        public string SDT { get; set; }
        public string SDT_Cu { get; set; }
        public string DiaChi { get; set; }
        public string DiaChi_Cu { get; set; }
        public string Email { get; set; }
        public string Email_Cu { get; set; }
        public string NguoiThayDoi { get; set; }
        public Nullable<System.DateTime> NgayThayDoi { get; set; }
        public string TrangThai { get; set; }
    }
}
