//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_anhchitietsanpham
    {
        public int Id { get; set; }
        public int Id_Sp { get; set; }
        public string DuongDan { get; set; }

        public string AnhSanPham { get; set; }

        public string TenSanPham { get; set; }
    }
}
