//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_giohang
    {
        public int Id { get; set; }
        public Nullable<int> Id_user { get; set; }
        public Nullable<int> Id_MaSanPham { get; set; }
        public Nullable<int> SoLuongSanPham { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<int> TrangThai { get; set; }

        public string AnhSanPham { get; set; }

        public string TenKhachHang { get; set; }

        public string TenSanPham { get; set; }
    }
}
