//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doanweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sanpham
    {
        public int Id { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public string ChiTietSanPham { get; set; }
        public Nullable<int> NhaSanXuat { get; set; }
        public string LoaiSanPham { get; set; }
        public string AnhSanPham { get; set; }

        public DateTime? NgayNhap { get; set; }

        public int? SoLuong { get; set; }

        public int? TrangThai { get; set; }

        public int? SoLuongSanPham { get; set; }

        public string Tennhasanxuat { get; set; }
    }
}
